import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../../globals.css";
import localFont from "next/font/local";

import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const sfPro = localFont({
  src: "../../../assets/font/SF-Pro-Display-Regular.woff",
  variable: "--font-sf",
});

export const metadata: Metadata = {
  title: "Nutriscan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-gray-100",
          sfPro.variable
        )}
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
